### ISSUE TITLE
Error when voting in Slack

### ISSUE THREAD

**Issue by dclear** [dgurkaynak/slack-poker-planner#10]
Hi @dgurkaynak - starting yesterday, we get the following error in Slack on submit of a vote:

`Could not parse callback_id "vote_jG6l1R_j"`

Thanks.

**Comment by dgurkaynak** [comment]
Hey @dclear, thanks for reporting. The issue was when generated id contains `_` (underscore) character, it brakes the string parsing back from slack's callback id. I've just fixed it and deployed already.

**Comment by dclear** [comment]
Fantastic, thanks for the quick response!
