### ISSUE TITLE
Customizable poker values per channel

### ISSUE THREAD

**Issue by dgurkaynak** [dgurkaynak/slack-poker-planner#12]
This is a feature request I've received from e-mail.

Feel free to add your reaction or comment.

**Comment by dgalezow** [comment]
That would be great!

**Comment by dgurkaynak** [comment]
This feature is implemented in [v1.0.0-beta.2 release](https://github.com/dgurkaynak/slack-poker-planner/releases/tag/1.0.0-beta.2).
