### ISSUE TITLE
Voting includes sender when using @user syntax

### ISSUE THREAD

**Issue by c0diq** [dgurkaynak/slack-poker-planner#14]
When using the syntax `/pp text @user1 @user2` the bot will also include the user who typed the message. Usually the scrum master is not voting. If user writing the message wishes to be part of the voting its username should be added to the list instead.

**Comment by dgurkaynak** [comment]
That's a valid request, and it makes sense that if you're explicitly mentioning the participants, you need to mention yourself explicitly if you want to participate 👍 I will look into this when I've spare time.

**Comment by dgurkaynak** [comment]
Hey @c0diq, this is fixed & deployed 🚀  Can you please try it?

**Comment by c0diq** [comment]
It works. Thank you very much!
