### ISSUE TITLE
Average Results Config Option

### ISSUE THREAD

**Issue by BrockBelmonte** [dgurkaynak/slack-poker-planner#15]
Ability to take the average of all of the votes and reveal the average with the individual answers (Only if all options are numeric)

Example: 

User votes: 

1
4
2
6
Average: 3.25 (Or 3 rounded if you do not want to support decimals)

Thank you in advance for looking into this, the bot is great!

**Comment by dgurkaynak** [comment]
This is doable, but I'm not sure that would be a great fit for the project. First of all, as you mentioned, there can be non-numeric values, such as `∞` or `?`. More than that, these values can be customized for each workspace, some workspaces are using just emoji answers.

Another thing is, I think there is no need to taking an average because most of the poker planning sessions are performed by small groups (< 10 people). According to my experiences, there is generally some kind of consensus, and the outlier answers are easily spotted at a glance.

**Comment by BrockBelmonte** [comment]
That makes total sense, just thought it could be a cool addition as an option to use if a user wanted to include it. I guess it could be a bit of a small group who actually enable that feature and use it as it definitely would not apply to all situations. 

Thank you so much for your quick response and consideration, I really appreciate it!

**Comment by dgurkaynak** [comment]
Thank you for recommending this 👍 I'm leaving this issue open, so people can come and upvote this feature.

**Comment by Jackseed** [comment]
Average result would be really cool! If it's implemented, a way to chose the result calculation parameter so we may also use median instead of sum would be great.

**Comment by Sergej-Popov** [comment]
From experience, it really streamlines the decision-making process and we only talk about the score in more details if there are outliers and/or someone disagrees.

Understandably, the average/median would only be available only for numeric entries, but still, it helps a lot. For example, [PlanITpoker](https://www.planitpoker.com/) ignores non-numeric values and calculates what it can.


I'm happy to implement this if you confirm that you will accept the PR.

**Comment by dgurkaynak** [comment]
@Sergej-Popov It would be great! 

I think we can add a single line to the result message, I don't want to cause visual clutter. But should we indicate which values are non-numeric and ignored while calculating the average. What's on your mind?

**Comment by Sergej-Popov** [comment]
Yes @dgurkaynak , a single line that shows average & median results is enough.
Here is what I propose:
In the new session form under section `Other (optional)` to add an additional checkbox option:

- [ ] Calculate the average (only numeric points will be used)

Given user has selected the option in the result window an additional single line will show the result:
```
Result:
1 person voted 8 (people list)
2 people voted 3 (people list)
4 people voted 2 (people list)
1 person voted ☕ (people list)
Average: 3.1
```
Average to be rounded to 1 decimal point.
Can also include the median, but IMHO it just adds clutter.
`Average: 3.1 Median: 2`

**Comment by dgurkaynak** [comment]
@Sergej-Popov sounds great! I definitely agree with you about not including median 👍

**Comment by dgurkaynak** [comment]
Hey guys, I've merged @Sergej-Popov's pull request and just deployed it. So this feature is now live. Thanks again @Sergej-Popov 🙌

**Comment by Sergej-Popov** [comment]
Thanks, for the great app! :)
