### ISSUE TITLE
Add ability to make the buttons no-op for anyone but the author

### ISSUE THREAD

**Issue by tomasztucholski** [dgurkaynak/slack-poker-planner#19]
It might be configurable or default, but it would really help make the buttons no-op for anyone but the author of the vote.

**Comment by dgurkaynak** [comment]
Why do you need this?

**Comment by tomasztucholski** [comment]
Currently the buttons are big and red (especially on Slack's dark theme) and very enticing for people to click. Every time a new person is introduced to the tool they ruin at least some of the votes by clicking "Reveal" on "Cancel", not knowing that it will end the vote and show all of the answers.
From time to time existing users click the buttons by mistake too, exposing half-finished votes and causing confusion.

**Comment by dgurkaynak** [comment]
I can understand the confusion of the new people, which shouldn't last long. However, I didn't think about accidental clicks, this is a legit request 👍 So, I'm leaving this issue open. If there are enough requests, we can implement it.

**Comment by dgurkaynak** [comment]
@tomasztucholski I've just shipped [a big release](https://github.com/dgurkaynak/slack-poker-planner/releases/tag/1.0.0-beta.2) with an ability to `protect sessions`. You can read the release notes for further details. So I'm closing this issue, let me know if you need anything.
