### ISSUE TITLE
Error: channel_not_found

### ISSUE THREAD

**Issue by andrey-nc** [dgurkaynak/slack-poker-planner#2]
Repro steps:
1. Open private channel
2. Type "/pp test @user1 @user2"
3. See chat message from Poker Planner APP with text "channel_not_found"

**Comment by janderberg** [comment]
I got the same error using a channel that is shared between multiple workspaces.

**Comment by dgurkaynak** [comment]
Hey guys, I can not reproduce this issue. 

1. Created new private channel
2. `/pp test @user1 @user2` worked for both cases:
     - user1 and user2 are members of the channel
     - user1 and user2 are **not** members of the channel

Can you reproduce this issue everytime or does it work sometimes?

**Comment by janderberg** [comment]
My apologies, my Slack admin already uninstalled the app and I do not have access to install and test it in that Slack environment myself. But when I had it installed, I only tried with a private shared channel, and from what I recall I was getting this error when specifying users and when I didn't specify users.

**Comment by dgurkaynak** [comment]
I finally managed to trace and reproduce this issue. This is happened on private channels when app is installed by someone who does not have permission to that channel. To fix this, app needs to re-installed by a user who has access to that private channel/group. (This process renews the access token of the team.)

When this occurs, Poker Planner is now printing an instruction for fix.

![image](https://user-images.githubusercontent.com/1475786/66134358-e3568f00-e600-11e9-8ce4-c952b42237cc.png)
