### ISSUE TITLE
Unexpected Slack API Error: "user_not_found"

### ISSUE THREAD

**Issue by rrollins** [dgurkaynak/slack-poker-planner#20]
Unexpected Slack API Error: "user_not_found"

error id: rABflyn8E

**Comment by dgurkaynak** [comment]
Hmm, when the app is trying to fetch the presence (online/offline status) of all the members of a channel, it seems Slack API couldn't find (at least) one specific user.  Do you have some kind of guest user in that channel?

**Comment by rrollins** [comment]
@dgurkaynak yes it's a shared channel

**Comment by rrollins** [comment]
@dgurkaynak let me know my dude if you're able to get to this.  my team can really use it.

**Comment by dgurkaynak** [comment]
I'll try to look into this on weekend.

**Comment by dgurkaynak** [comment]
@rrollins I've just shipped [a big release](https://github.com/dgurkaynak/slack-poker-planner/releases/tag/1.0.0-beta.2) which should fix this issue. Can you please try again and confirm?

**Comment by dgurkaynak** [comment]
@rrollins I'm closing this issue. If the problem persists, feel free to open it again.
