### ISSUE TITLE
A button to restart voting session after reveal

### ISSUE THREAD

**Issue by dgurkaynak** [dgurkaynak/slack-poker-planner#24]
Received from e-mail, feel free to add your reaction or comment.

**Comment by Sergej-Popov** [comment]
Can just create a new session. All options are memorized so it is very simple.
The benefit of making a new session is that the user can see if the result & votes are different.

**Comment by nraj-willow** [comment]
Please add this feature, Today I accidentally clicked reveal and there is no way to unreveal results.

**Comment by sprak3000** [comment]
While it is easy to create a new session, it results in additional clutter in a channel. This could be reduced if Slack allowed slash commands in threads. Today is not that day though.

I would be in favor of this feature with the ability to see the previous votes / results. Maybe cap it though to no more than the previous one or two rounds along with the current set of results.

That said, our team is loving this tool. We greatly appreciate your work on it!

**Comment by dgurkaynak** [comment]
Hey guys, this feature is implemented with 2.0.0 release, and it's already deployed 🚀 
Now, you can restart a session with a button after it's revealed.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/1475786/189524708-ccf781b1-e7e1-4e04-864b-820f847df256.png">
