### ISSUE TITLE
Default points set includes "1/2", which does not work with average option

### ISSUE THREAD

**Issue by tjp502** [dgurkaynak/slack-poker-planner#29]
With the average option turned on, "1/2" is identified as a numeric value, and so counted towards the calculation, but incorrectly parsed as `1.0`.

This could be considered a bug, or simply a limitation of the system that people have to work around (e.g. by replacing the point with "0.5"), but as "1/2" is in the set of default points, this probably needs addressing one way or another.

**Comment by dgurkaynak** [comment]
Hmm, yeah you are right. I guess we can change the default value to `0.5` 👍
