### ISSUE TITLE
Show who has already voted

### ISSUE THREAD

**Issue by adi27** [dgurkaynak/slack-poker-planner#3]
As a user I would like to see who already participated in a vote to be able to close a poll if enough votes have been collected. Currently if one person is away the vote will hang and one has no information about current voting status.

**Comment by dgurkaynak** [comment]
Hey @adi27, this is a requested feature but I am not planning to implement due to lack of time. Any pull requests are welcome.

**Comment by adi27** [comment]
It is, but maybe if the project is open source, then such a request should be left open, then someone might want to implement it in the future?

**Comment by dgurkaynak** [comment]
Yeah, you're right 👍

**Comment by dgurkaynak** [comment]
Hey @adi27, I've implemented this feature and just shipped it. Can you please try and confirm it?

**Comment by douglasjam** [comment]
it works, thank you! big improvement

**Comment by adi27** [comment]
Sorry for late reply. It works very good, thank you!
