### ISSUE TITLE
batch votes

### ISSUE THREAD

**Issue by joeyfezster** [dgurkaynak/slack-poker-planner#32]
Hi,
I don't know if this is the best way to request a feature (and sorry if it's not) - but here goes:

# Batch creation of voting sessions.
## Context:
1. We use an external task mgmt tool (clubhouse), and also run as a fully remote team.
1. we can get a list of permalinks to all tasks requiring estimation from the tasks manager / or a simple scraper
1. We're looking for an easy way to do estimations asynchronously, so the PM can deploy X voting sessions to the team (1 per task/ticket/story -name depends on your tool)

## Feature request:
Given a list of "issue titles" (that are actually links), a constant group of people (either by @team, or @individual1, @individual2... @individualN), and a constant set of "cards" (0.5, 1, 3, 5, 8, ☕ ,...) - allow me to create multiple estimation requests.

## Impact:
Productivity - it becomes much easier to do sprint planning, as via this feature, the call to action to review and estimate tickets can take seconds not hour++.

**Comment by dgurkaynak** [comment]
Hey @joeyfezster, it's definitely the correct place to request a feature; you're very welcome. This is the first time I got this feature request. If there are enough upvotes or requests, we'll see what we can do. Maybe we can convert the session title input to a multiline textarea, and if some option is checked, the app will create a separate session for each line entered.

**Comment by fidalgo** [comment]
This is an awesome idea, I landed here for the same request :)

**Comment by dgurkaynak** [comment]
Hey guys, this feature is implemented with 2.0.0 release, and it's already shipped 🚀 
Now, you can create multiple voting sessions by separating them into a new line (up to 10 sessions).

<img width="542" alt="image" src="https://user-images.githubusercontent.com/1475786/189524887-b9c5a8df-0dbc-4f12-af9b-be4cd75fd650.png">
