### ISSUE TITLE
[Question] How can I use API to trigger /pp command

### ISSUE THREAD

**Issue by hanks** [dgurkaynak/slack-poker-planner#33]
Hi,

I installed pp with `https://deniz.co/slack-poker-planner/`, and want to use API to trigger `/pp title` in script, but do not know how to do that.

I believe I need to find the `request url` like `http://my.awesome.project.url/slack/pp-slash-command`, and also find the oauth token for that call.

Thanks for your time.

**Comment by dgurkaynak** [comment]
Hi @hanks, 

Unfortunately, that's not possible. Slack has a verification token that sends to our API in every request, and we reject all the requests with an invalid token as Slack suggests.
