### ISSUE TITLE
Set a timer to reveal the vote session automatically?

### ISSUE THREAD

**Issue by hanks** [dgurkaynak/slack-poker-planner#37]
Hi,

Just wondering:

1. is there such a feature to reveal the vote session automatically, because sometimes we do not want to wait for all the people to vote
2. if option 1 is not implemented right now, is there any API to simulate to click the reveal button? So we can call it by ourself

Thanks

**Comment by dgurkaynak** [comment]
1. There is no such feature. That would require timer handling, which adds great complexity to the code. Setting timer is not an issue, but we need to some-kind-of persist it, so it can recover from crashes/restarts.
2. There is no public API. The current API is only for Slack API usage.

I'm not sure, but I feel like option 1 fits better in this product. I'm leaving this issue open, if there are enough requests, we can consider implementing it.

**Comment by musab** [comment]
+1 on "reveal the vote session automatically" - is there anyway I can help on this feature?

**Comment by dgurkaynak** [comment]
Hey guys, I've implemented customizable voting end timers with 2.0.0 release, and it's already deployed 🚀 
Now you can specify a custom time duration to a voting session. After the timer is up, it's auto-revealed.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1475786/189524594-7f8ac882-b1f0-46ee-82ba-5821efc37d53.png">
