### ISSUE TITLE
action cancel

### ISSUE THREAD

**Issue by douglasjam** [dgurkaynak/slack-poker-planner#4]
Would be cool to have a new feature: "Cancel voting", it would abort the poll and do not reveal the votes, currently we have no choice to do not show it, just revealing.

**Comment by dgurkaynak** [comment]
This is a reasonable request, and I guess it will be easy to implement it. I will look into this 👍

**Comment by dgurkaynak** [comment]
Hey @douglasjam, I've just implemented and shipped this feature. Could you please try?

**Comment by douglasjam** [comment]
It works as expected, thanks again! 👍
