### ISSUE TITLE
Add a dismiss option to delete poker planner message

### ISSUE THREAD

**Issue by mpellerin42** [dgurkaynak/slack-poker-planner#41]
We run our planning poker session in our squad channel in slack, and once the session is finished and corresponding stories are updated, I like to clean up the channel by deleting the estimation messages. 
Poker planner app currently doesn't allow to do so, could a `Dismiss` button be added to delete the corresponding message on the channel?

**Comment by dgurkaynak** [comment]
I think we can do that, slack's [chat.delete](https://api.slack.com/methods/chat.delete) api allows it.

**Comment by dgurkaynak** [comment]
Hey @mpellerin42, this feature is implemented with 2.0.0 release, and it's already deployed 🚀 
Now, you can delete a voting session's message after it's revealed.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/1475786/189524708-ccf781b1-e7e1-4e04-864b-820f847df256.png">

**Comment by mpellerin42** [comment]
Awesome! thanks for the update @dgurkaynak
