### ISSUE TITLE
Option to automatically reveal the session before it expires

### ISSUE THREAD

**Issue by calvis** [dgurkaynak/slack-poker-planner#43]
From the website:
> All the not-finished sessions are kept in a database for 7 days. After that they're completely deleted.

I'd like the option to have those sessions automatically revealed before they are completely deleted. Otherwise, I have to keep track of all of the open sessions and make sure I hit the "Reveal" button before the 7 days are up.

This seems related to #37, except I'm not interested in a custom timer, so I don't think it'd require any extra persistent data.

**Comment by dgurkaynak** [comment]
It's certainly doable. And it will be easier than custom timer as you've said.

**Comment by dgurkaynak** [comment]
Hey @calvis, I've implemented customizable voting end timers with 2.0.0 release, and it's already deployed 🚀 
Now you can specify a custom time duration to a voting session. After the timer is up, it's auto-revealed.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1475786/189524594-7f8ac882-b1f0-46ee-82ba-5821efc37d53.png">
