### ISSUE TITLE
'Internal server error, please try again later' error message encountered when other slack bots are in the same channel

### ISSUE THREAD

**Issue by vitx0001** [dgurkaynak/slack-poker-planner#5]
We have a custom slack bot in our channels.  When we try poker planner it gives an error of 'Internal server error, please try again later'.  When we remove all bots from the channel, then the poker planner works.

**Comment by dgurkaynak** [comment]
Hey @vitx0001, what is your slack team id and when did this issue occurred?

**Comment by jeremy-j-ackso** [comment]
I've been getting this same problem. We are not self-hosting.

**Comment by dgurkaynak** [comment]
Hey @jeremy-j-ackso, thanks for reporting. Can you help me to reproduce this issue?
- Which type of channel are you using on? (public or private channel?)
- Do you use any other bots/apps on your slack? If so, what are they?

**Comment by jeremy-j-ackso** [comment]
* It's a private channel.
* We have a ton of apps since this is for our mid-size company, and different teams have different needs. I can't easily get a list, but ballpark would be ~40.

**Comment by dgurkaynak** [comment]
Hey guys, I've just fixed an issue related with starting sessions on private channels/groups when app is installed by someone who does not have permission to that channel. It may fix this `Internal server error` issue, however I'm not sure. 

I've also added error code and unique id to error messages. If you encounter this error again, can you report that error? So I can trace more deeply.

**Comment by dgurkaynak** [comment]
Due to no response, I'm closing this issue. Please reopen if it happens again.
