### ISSUE TITLE
Unexpected Slack API Error

### ISSUE THREAD

**Issue by UnbannableShnurD6** [dgurkaynak/slack-poker-planner#61]
An error popped up after clicking the button with number (rating):

`Unexpected Slack API Error: "fatal_error", please try again later (error code: _zql8Qusr).`

The error occurred once and did not bother me anymore.

**Comment by phatpt8** [comment]
It has happened in our organisation as well.
```
Unexpected Slack API Error: "fatal_error", please try again later (error code: oZCHqLDTR)
```

**Comment by dgurkaynak** [comment]
Hey guys, thanks for reaching out. As @phatpt8 pointed out, it's an Slack related error. Slack doesn't respond our service's API requests. Since we have nothing to do but wait, I'm closing this issue.
