### ISSUE TITLE
Allow button text with spaces

### ISSUE THREAD

**Issue by paulera** [dgurkaynak/slack-poker-planner#63]
### Steps to reproduce

Create a poll with the following list of options

`0 1 2 singletext text-with-dash text_with_underline 🐝 :star: "text with spaces" ":smile: smile shortcode" "😀 happy unicode"`

### Current result

![image](https://user-images.githubusercontent.com/2051955/170998776-1b5e21fc-5516-4664-abcb-7d2316ed8437.png)

### Expected result

`"text with spaces"`, `":smile: smile shortcode"` and `"😀 happy unicode"` produce a single button each.

**Comment by dgurkaynak** [comment]
Hey @paulera, this feature is implemented with 2.0.0 release, and it's already deployed 🚀 
Now, you can use whitespaces inside double or single quotes.
