### ISSUE TITLE
Make app resilient to a restart requiring re-auth in Slack

### ISSUE THREAD

**Issue by SteveGoodenough** [dgurkaynak/slack-poker-planner#67]
I'm running poker-planner within a kubernetes cluster with the result that if k8s decides to restart the app or if using preemptible nodes (cheaper but get restarted at least once every 24 hours)  then the authorisation is lost and you cannot run poker-planner in Slack without having to re-auth it (requiring an admin to approve).

As an alternative to using the oauth call to authorise the app could an alternative approach be used to pass the authorisation tokens into the container as part of the dockerfile for example (or I'd use a configmap) so the authorisation is static and the app resilient to restarts (although the current sessions would be lost...which is fine as they generally are short lived).

**Comment by dgurkaynak** [comment]
Hey @SteveGoodenough, you need to mount a persistent data folder to containers. We're saving access tokens in a sqlite file. See: 
- https://github.com/dgurkaynak/slack-poker-planner/blob/master/.env#L18-L19
- https://github.com/dgurkaynak/slack-poker-planner/blob/master/README.md?plain=1#L58-L59

**Comment by SteveGoodenough** [comment]
oh that's cool, sorry for missing that, I'll take a look.

Thanks for the quick reply too
