### ISSUE TITLE
Link as title is broken now

### ISSUE THREAD

**Issue by mrauscheder** [dgurkaynak/slack-poker-planner#69]
We always use the link to jira as title:

`/pp https://jira.website.com/browse/TL-11316` produced:
Title: [https://jira.website.com/browse/TL-11316](https://jira.website.com/browse/TL-11316)

But now PokerPlanner adds some angle brackets to the title if you use a link as title.
In the dialog that opens after using the /pp command, the title would be `<https://jira.website.com/browse/TL-11316>`

That would not be a problem, but the output after starting the session is broken and looks like this:

`<https://jira.website.com/browse/TL-11316>`
https://jira.website.com/browse/TL-11316%3E

But it should be:
https://jira.website.com/browse/TL-11316

**Comment by dgurkaynak** [comment]
Hey @mrauscheder, this issue should be fixed now. Thanks for the bug report 👍
Let me know if you need anything else.
