### ISSUE TITLE
Internal server error, please try again later When I requested /pp

### ISSUE THREAD

**Issue by RadekAm** [dgurkaynak/slack-poker-planner#7]
Hi,

when I've tried to request /pp in a private channel I got "Internal server error, please try again later" message.

Thanks,

RA

**Comment by dclear** [comment]
Same here

<img width="508" alt="Screen Shot 2019-07-02 at 2 27 53 PM" src="https://user-images.githubusercontent.com/1197912/60546915-a1edd500-9cdb-11e9-9410-af2b12c8bc0d.png">

**Comment by dgurkaynak** [comment]
Hey, all the processes in my server got killed somehow. I just restarted all of them and it's working now. Thanks for letting me know 👍
