### ISSUE TITLE
Encoding problems on restart voting

### ISSUE THREAD

**Issue by lzientek** [dgurkaynak/slack-poker-planner#70]
Hello,
First great work on this slack app !
We are using it and we found a small bug on the restart voting feature that encodes the title in html entities one more time.

Step to reproduce create a with a PP with the title " < something > " then restart voting and it will give you the title "&lt; something &gt;" and so on.

real exemple here.
![image](https://user-images.githubusercontent.com/3025360/199949349-46f09ebe-f647-4083-85eb-4d079395e5cb.png)

Best regards the mistertemp' team!

**Comment by dgurkaynak** [comment]
Hey @lzientek, this issue should be fixed now. Thanks for the bug report 👍
Let me know if you need anything else.
