### ISSUE TITLE
session initiated by API call

### ISSUE THREAD

**Issue by AriLFrankel** [dgurkaynak/slack-poker-planner#73]
Howdy
I'm wondering if there's a way to start a poker-planner session by API call, or if there's a plan to support this in the future. The use case is that I'm using a Jira -> Slack integration, and I would like to initiate a poker-planner session for tickets as they are moved through certain lifecycle events using the Jira -> Slack integration

**Comment by dgurkaynak** [comment]
Hey @AriLFrankel, 

It's theoretically possible, but it brings huge security concerns. Therefore I am not planning to implement any APIs for programmatic usage. Thanks for reaching out. If you're interested in forking your own version, I can happily fill you in on how to implement this.

**Comment by gtabrar** [comment]
@AriLFrankel did you find a solution for this using an alternative? I love this poker planner but having to manually invoke it for every new ticket in a sprint is a non-starter for us.
