### ISSUE TITLE
502_service_error on new game submit

### ISSUE THREAD

**Issue by dclear** [dgurkaynak/slack-poker-planner#8]
When posting a new game in channel (starting today), it’s rejecting my game submissions with: 

<img width="508" alt="Screen Shot 2019-07-02 at 2 27 53 PM" src="https://user-images.githubusercontent.com/1197912/60547149-3a845500-9cdc-11e9-90e6-62faae1a6eed.png">

Your app is very useful, by the way, thank you.

**Comment by dgurkaynak** [comment]
See #7

**Comment by dclear** [comment]
ty!
